CREATE TABLE authors
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(100)                             NOT NULL,
    CONSTRAINT pk_authors PRIMARY KEY (id)
);

CREATE TABLE book_authors
(
    author_id INTEGER NOT NULL,
    book_id   INTEGER NOT NULL
);

CREATE TABLE books
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    isbn         VARCHAR(50)                              NOT NULL,
    url_cover    VARCHAR(255),
    title        VARCHAR(100)                             NOT NULL,
    id_category  INTEGER                                  NOT NULL,
    id_publisher INTEGER                                  NOT NULL,
    synopsis     TEXT,
    year         INTEGER,
    page_count   INTEGER,
    quantity     INTEGER                                  NOT NULL,
    CONSTRAINT pk_books PRIMARY KEY (id)
);

CREATE TABLE books_rental
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_reader      INTEGER                                  NOT NULL,
    start_date     TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    predicted_date TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    final_date     TIMESTAMP WITHOUT TIME ZONE,
    status         VARCHAR(100)                             NOT NULL,
    CONSTRAINT pk_books_rental PRIMARY KEY (id)
);

CREATE TABLE categories
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(100)                             NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE exemplars
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    inventory_number VARCHAR(255)                             NOT NULL,
    book_id          INTEGER                                  NOT NULL,
    book_rental_id   INTEGER,
    status           VARCHAR(100)                             NOT NULL,
    CONSTRAINT pk_exemplars PRIMARY KEY (id)
);

CREATE TABLE publishers
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(100)                             NOT NULL,
    CONSTRAINT pk_publishers PRIMARY KEY (id)
);

CREATE TABLE readers
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(100)                             NOT NULL,
    email        VARCHAR(50)                              NOT NULL,
    phone_number VARCHAR(50)                              NOT NULL,
    CONSTRAINT pk_readers PRIMARY KEY (id)
);

CREATE TABLE users
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(100)                             NOT NULL,
    email    VARCHAR(50)                              NOT NULL,
    password VARCHAR(100)                             NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE books
    ADD CONSTRAINT uc_books_isbn UNIQUE (isbn);

ALTER TABLE books
    ADD CONSTRAINT FK_BOOKS_ON_ID_CATEGORY FOREIGN KEY (id_category) REFERENCES categories (id);

ALTER TABLE books
    ADD CONSTRAINT FK_BOOKS_ON_ID_PUBLISHER FOREIGN KEY (id_publisher) REFERENCES publishers (id);

ALTER TABLE books_rental
    ADD CONSTRAINT FK_BOOKS_RENTAL_ON_ID_READER FOREIGN KEY (id_reader) REFERENCES readers (id);

ALTER TABLE exemplars
    ADD CONSTRAINT FK_EXEMPLARS_ON_BOOK FOREIGN KEY (book_id) REFERENCES books (id);

ALTER TABLE exemplars
    ADD CONSTRAINT FK_EXEMPLARS_ON_BOOK_RENTAL FOREIGN KEY (book_rental_id) REFERENCES books_rental (id);

ALTER TABLE book_authors
    ADD CONSTRAINT fk_booaut_on_author FOREIGN KEY (author_id) REFERENCES authors (id);

ALTER TABLE book_authors
    ADD CONSTRAINT fk_booaut_on_book FOREIGN KEY (book_id) REFERENCES books (id);